### ISSUE TITLE
haproxy 1.5

### ISSUE THREAD

**Issue by klaemo** [dockerfile/haproxy#1]
could you trigger a rebuild of the image so we get the latest haproxy?

thanks :)

**Comment by olemartinorg** [comment]
The haproxy package in Ubuntu 14.04 is not version 1.5 yet, and since it's an LTS release it probably never will be. So, triggering a rebuild of this image wouldn't result in a newer haproxy version.

But, I'll throw in a shameless plug for my own, slightly modified version: https://github.com/olemartinorg/haproxy-1.5
This will automatically rebuild when there are new haproxy packages available.

**Comment by klaemo** [comment]
1.5.3 is in trusty-backports, maybe this image could pull it from there.

I'll check out yours too :) thanks

**Comment by pilwon** [comment]
@klaemo @olemartinorg Try the latest image rebuilt for v1.5 (d1ec66fdc82d1b8e7fef5d493d34028f08939e93 & 1ae89ba448fd89202a00400c03901313e85b1054)

**Comment by klaemo** [comment]
Awesome, thanks! :)
